---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-creds-chartmuseum
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin
  target:
    name: repo-creds-chartmuseum
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        enableOCI: "false"
        name: chartmuseum-fredcorp
        type: helm
        username: root
        password: "{{ .password }}"
        url: https://chartmuseum.k8s-app.fredcorp.com
  data:
  - secretKey: password
    remoteRef:
      key: chartmuseum/k0s
      property: PWD
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
