---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubechecks-creds
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: kubechecks-creds
  data:
    - secretKey: KUBECHECKS_VCS_TOKEN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: github
        property: DEVOPS_ORG_PAT
        metadataPolicy: None
    - secretKey: KUBECHECKS_ARGOCD_API_TOKEN
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: argocd
        property: ARGOCD_ADMIN_TOKEN
        metadataPolicy: None