---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-vcs-token
spec:
  rules:
    - name: add-secret-envfrom
      match:
        resources:
          kinds:
            - Pod
          selector:
            matchLabels:
              app.kubernetes.io/instance: kubechecks-prod
              app.kubernetes.io/name: kubechecks
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - name: kubechecks
                envFrom:
                  - configMapRef:
                      name: "{{ request.object.spec.containers[0].envFrom[0].configMapRef.name }}"
                  - secretRef:
                      name: kubechecks-creds