---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k6-grafana
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: k0s
        namespace: k6-grafana
  template:
    metadata:
      name: 'k6-grafana-{{env}}'
      finalizers: []
    spec:
      project: ci-cd
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 3.*.*
        chart: k6-operator
        helm:
          releaseName: 'k6-grafana-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
