---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: renovate
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: k0s
        namespace: renovate
  template:
    metadata:
      name: 'renovate-{{env}}'
      finalizers: []
    spec:
      project: infra-core
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://docs.renovatebot.com/helm-charts
        targetRevision: '*'
        chart: renovate
        helm:
          releaseName: 'renovate-{{env}}'
          valuesObject:
            fullnameOverride: 'renovate-{{env}}'
            cronjob:
              schedule: '0 1 * * *' # At 01:00 every day
            existingSecret: 'github-creds'
            renovate:
              config: |
                {
                  "platform": "github",
                  "autodiscover": "true",
                  "automergeType": "pr",
                  "autodiscoverFilter": ["ixxeL-DevOps/*"]
                }
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
