---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-k8s
  namespace: argocd
spec:
  generators:
  - list:
      elements: []
      # - env: k0s
      #   namespace: vk-dev
      #   vcluster-env: dev
      # - env: k0s
      #   namespace: vk-prod
      #   vcluster-env: prod
  template:
    metadata:
      name: 'vcluster-k8s-{{vcluster-env}}'
      finalizers: []
    spec:
      project: vcluster
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://charts.loft.sh
        targetRevision: 0.*.*
        chart: vcluster-k8s
        helm:
          releaseName: 'vcluster-{{vcluster-env}}'
          valuesObject:
            serviceAccount:
              create: true
            ingress:
              enabled: true
              pathType: ImplementationSpecific
              apiVersion: networking.k8s.io/v1
              ingressClassName: "nginx"
              host: vcluster-{{vcluster-env}}.k8s-app.fredcorp.com
              annotations:
              #   cert-manager.io/cluster-issuer: vault-issuer
              #   cert-manager.io/common-name: vcluster.k8s-app.fredcorp.com
                nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
            syncer:
              extraArgs:
              - --tls-san=vcluster-{{vcluster-env}}.k8s-app.fredcorp.com
              kubeConfigContextName: vcluster-k8s-{{vcluster-env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
