---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: in-cluster
  namespace: argocd
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
stringData:
  name: k0s
  server: https://kubernetes.default.svc
type: Opaque