# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: github-creds
#   namespace: github-runner
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: admin
#     kind: ClusterSecretStore
#   target:
#     name: github-creds
#     creationPolicy: Owner
#   data:
#     - secretKey: github_token
#       remoteRef:
#         conversionStrategy: Default	
#         decodingStrategy: None
#         key: github
#         property: DEVOPS_ORG_PAT
#         metadataPolicy: None
