renovate:
  cronjob:
    schedule: '0 1 * * *' # At 01:00 every day
  existingSecret: 'github-creds'
  renovate:
    config: |
      {
        "platform": "github",
        "autodiscover": "true",
        "automergeType": "pr",
        "autodiscoverFilter": ["ixxeL-DevOps/*"]
      }

