---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-csi-retain"
  volumeName: adguard-pv