# ---
# apiVersion: external-secrets.io/v1alpha1
# kind: PushSecret
# metadata:
#  name: vk-cluster
#  namespace: argocd
# spec:
#   refreshInterval: 10s
#   secretStoreRefs: # A list of secret stores to push secrets to
#     - name: admin
#       kind: ClusterSecretStore
#   selector:
#     secret:
#       name: vk-pprod
#   data:
#   - match:
#       secretKey: config
#       remoteRef:
#         remoteKey: vcluster/pprod
#         property: config
#   - match:
#       secretKey: name
#       remoteRef:
#         remoteKey: vcluster/pprod
#         property: name
#   - match:
#       secretKey: server
#       remoteRef:
#         remoteKey: vcluster/pprod
#         property: server