# ---
# apiVersion: repo.github.upbound.io/v1alpha1
# kind: Repository
# metadata:
#   name: test
#   namespace: crossplane
# spec:
#   forProvider:
#     autoInit: true
#     gitignoreTemplate: Terraform
#     visibility: public
#   providerConfigRef:
#     name: github