---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certmanager-auth
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: certmanager-auth
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: "certmanager-auth"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.fredcorp.com
    path: pki_int/sign/fredcorp.com
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4VENDQXRtZ0F3SUJBZ0lVYktteExxQmtIUHJvaDdCckFTZitpQkdHS09zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FqRUxNQWtHQTFVRUJoTUNSbEl4RFRBTEJnTlZCQWdUQkU1dmNtUXhEakFNQmdOVkJBY1RCVXhwYkd4bApNUkV3RHdZRFZRUUtFd2hHVWtWRVEwOVNVREVMTUFrR0ExVUVDeE1DU1ZReEhEQWFCZ05WQkFNVEUyWnlaV1JqCmIzSndMbU52YlNCSlRsUWdRMEV3SGhjTk1qRXhNVEE0TVRNeE5ESXdXaGNOTXpZeE1UQXpNVE14TkRVd1dqQmwKTVFzd0NRWURWUVFHRXdKR1VqRU5NQXNHQTFVRUNCTUVUbTl5WkRFT01Bd0dBMVVFQnhNRlRHbHNiR1V4RVRBUApCZ05WQkFvVENHWnlaV1JqYjNKd01Rc3dDUVlEVlFRTEV3SkpWREVYTUJVR0ExVUVBd3dPS2k1bWNtVmtZMjl5CmNDNWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHVWeTNZR0dESUY2UysKVitJY2VRZnY2c2FhdU5hdVcyclM1TTdQeURRWE00dEJHTW15bTRoVjdkZjkxd2xEemc0cGNSQkg1M25uWUZjZgorenJ6Sm1WMFFNcE1MaGpUbTVWUDI1LzVPZklESzlCTXBRR0wzQVlZS0NwYmd5NVRNVC91WTBNTDZwQ2cybVFZCmtKQjhoQlBTOGt3QmliTHVyaytMN0R5cVhoRHVtMi9keU84UGFNeUV4OGpCWGMwRGhsb2lHQWtOSFBFTFFjTFoKeEtEWHBOQVFueXRDWHRGQ3dzNUlrREEwTi9UZjlyK0NKZEVhU3h1Tmd4MXg2bVBDSVovS2t0VUZGcHdhK0J4Mgpvdk94V0NRaGhRMTlEWDJPZlpqSTNQaXdRaHpiR21jK25oNGxHa0FKK25uclhYRXdsWE9ZS01IbWp0MU1YZnZECmxMNHVTa29sQWdNQkFBR2pnWk13Z1pBd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFkQmdOVkhRNEVGZ1FVY1ZmZC80cDBwZWhpckpSbmdSdlZ1eDVwTEZndwpId1lEVlIwakJCZ3dGb0FVM3Q2WHY2RHVCVHNRVGwwNnlod2dMWG1reGpVd0h3WURWUjBSQkJnd0ZvSU9LaTVtCmNtVmtZMjl5Y0M1amIyMkhCQUFBQUFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJQ0g2RlkwMnVhSXhTdEQKbEVXd0dRcFZsdG0wMjJwWjdwVTBXVXJIckREdnFVTndwWURzU3BNWWdpTExLbkViaHBiNWllTnNOZTNncUZPWgpYMDdrWjBzRDlKWUJFOWhRUWxOZlhFNm5VV3BIbnV1Mi8zUTdhVVNRQ2phZkIzbnZtVDJLTkRSQnNKd3JINkJYClM4RGY2cWhxeWFPd0duMjhoOEdVQmFLRWkzMjhQT0JHNW9VQ2RDRWpIek52ckRJeUFsenpNOUtLMGNJNVk0cEEKWnk4VVI2cUtwZDBSRktRaGk0VEdMRVFQYW9QQnNURGRZOWQyclB0WTk0Rll5REJHdVhvNUhjSERTSnZydUxIbQprVGRRS29UdWtNSi91WE8vUWd1QzArbFdza25ROXVPUmRmOUpHLzdRUjM3UGxLd0FqOUx3OFgyT2RTdHVlNkQ2CjBacUpsY1k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        secretRef:
          name: certmanager-auth
          key: token