kubechecks:
  # Labels to apply to all resources created by this Helm chart
  argocd:
    namespace: argocd

  configMap:
    create: true
    env:
      KUBECHECKS_ADDITIONAL_APPS_NAMESPACES: "*"
      KUBECHECKS_ARGOCD_API_INSECURE: "true"
      KUBECHECKS_ARGOCD_API_PATH_PREFIX: /
      KUBECHECKS_ARGOCD_API_NAMESPACE: argocd
      KUBECHECKS_ARGOCD_WEBHOOK_URL: https://argocd.k8s-infra.fredcorp.com/api/webhook
    # KUBECHECKS_FALLBACK_K8S_VERSION: "1.22.0"
      KUBECHECKS_LOG_LEVEL: debug
      KUBECHECKS_NAMESPACE: kubechecks
      KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.k8s-app.fredcorp.com.
    # KUBECHECKS_WEBHOOK_URL_PREFIX: kubechecks
      KUBECHECKS_ARGOCD_API_SERVER_ADDR: argocd.k8s-infra.fredcorp.com
      ARGOCD_EXEC_TIMEOUT: 600s
    # KUBECHECKS_OTEL_COLLECTOR_PORT: "4317"
    # KUBECHECKS_OTEL_ENABLED: "true"
      KUBECHECKS_VCS_TYPE: "github"
    # KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: "hide" # other options delete

  secrets:
    create: false
    name: kubechecks-creds
    # envs can be used for writing sensitive environment variables
    # to the secret resource. These should be passed into the
    # deployment as arguments.
    env: {}
    # KUBECHECKS_VCS_TOKEN: <token>

  ingress:
    create: true
    className: "cilium"
    annotations:
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: kubechecks.k8s-app.fredcorp.com
    hosts:
      kubechecks.k8s-app.fredcorp.com:
        paths:
          - path: "/"
            pathType: Prefix
    tls:
     - secretName: kubechecks-tls-cert
       hosts:
       - kubechecks.k8s-app.fredcorp.com

