---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: talos
        namespace: kube-system
  template:
    metadata:
      name: 'csi-driver-nfs-{{env}}'
      finalizers: []
    spec:
      project: infra-core
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
        targetRevision: v4.*.*
        chart: csi-driver-nfs
        helm:
          releaseName: 'csi-driver-nfs-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: storage.k8s.io
          kind: CSIDriver
          jqPathExpressions:
            - .spec.seLinuxMount

