---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-web-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: ixxeL-DevOps
          repo: demo-web-py
          tokenRef:
            key: github_token
            secretName: github-creds
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'demo-web-pr-{{number}}'
      annotations:
        notifications.argoproj.io/subscribe.on-ephemeral-deployed.github: ""
        notifications.argoproj.io/subscribe.on-ephemeral-health-degraded.github: ""
        notifications.argoproj.io/subscribe.on-ephemeral-sync-failed.github: ""
        notifications.argoproj.io/subscribe.sync-operation-change.rocketchat: "#vcluster-preview"
    spec:
      destination:
        namespace: 'demo-web-pr-{{number}}'
        name: 'vk-preview'
      project: ephemeral
      source:
        path: deploy/
        repoURL: 'https://github.com/ixxeL-DevOps/demo-web-py.git'
        targetRevision: '{{branch}}'
        helm:
          releaseName: 'demo-web-pr-{{number}}'
          valuesObject:
            demo-web:
              fullnameOverride: 'demo-web-pr-{{number}}'
              image:
                registry: docker.io
                repository: ixxel/demo-web
                tag: 'sha-{{head_sha}}'
              ingress:
                enabled: true
                className: "cilium"
                annotations:
                  cert-manager.io/cluster-issuer: vault-issuer
                  cert-manager.io/common-name: 'demo-web-pr-{{number}}.k8s-app.fredcorp.com'
                hosts:
                  - host: 'demo-web-pr-{{number}}.k8s-app.fredcorp.com'
                    paths:
                      - path: /
                        pathType: Prefix
              test: 
                enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 2 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/instance: 'demo-web-pr-{{number}}'
          annotations:
            argocd.argoproj.io/tracking-id: >-
              demo-web-pr-{{number}}:/Namespace:demo-web-pr-{{number}}/demo-web-pr-{{number}}
      info:
      - name: url
        value: 'https://demo-web-pr-{{number}}.k8s-app.fredcorp.com/'
