---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: talos
        namespace: external-secrets
  template:
    metadata:
      name: 'external-secrets-{{env}}'
      finalizers: []
    spec:
      project: infra-security
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: 0.10.7
        chart: external-secrets
        helm:
          releaseName: 'external-secrets-{{env}}'
          valuesObject:
            fullnameOverride: external-secrets-{{env}}
            installCRDs: true
            crds:
              createClusterExternalSecret: true
              createClusterSecretStore: true
              createPushSecret: true
              conversion:
                enabled: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
