---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitlab-runner
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: 'https://github.com/ixxeL-DevOps/GitOps-home.git'
      revision: main
      directories:
        - path: 'talos/apps/gitlab-runner/*'
          exclude: false
  template:
    metadata:
      name: 'gitlab-runner-{{ .path.basenameNormalized }}'
    spec:
      project: infra-pipelines
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: gitlab-runner
      source:
        repoURL: 'https://github.com/ixxeL-DevOps/GitOps-home.git'
        path: '{{.path.path}}'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
