---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hydrator-app
  namespace: argocd
spec:
  project: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sourceHydrator:
    drySource:
      repoURL: 'https://github.com/ixxeL-DevOps/GitOps-apps.git'
      path: 'envs/vk-uat/namespaces/helm-promote/apps/demo-web'
      targetRevision: main
    syncSource:
      targetBranch: stage/uat
      path: 'envs/vk-uat/namespaces/helm-promote/apps/demo-web'
    hydrateTo:
      targetBranch: stage/uat-next
