---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hydrator-app
  namespace: argocd
spec:
  project: ephemeral
  destination:
    name: prod
    namespace: default
  sourceHydrator:
    drySource:
      repoURL: 'https://github.com/ixxeL-DevOps/GitOps-apps.git'
      path: 'envs/vk-uat/namespaces/helm-promote/apps/demp-web'
      targetRevision: main
    syncSource:
      targetBranch: environments/uat
      path: 'envs/vk-uat/namespaces/helm-promote/apps/demp-web'
    hydrateTo:
      targetBranch: environments/uat-next
