---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: uat
      - env: prod
  template:
    metadata:
      name: kargo-demo-{{env}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{env}}
    spec:
      project: ci-cd
      source:
        repoURL: 'https://github.com/ixxeL-DevOps/GitOps-apps.git'
        targetRevision: deploy/{{env}}
        path: kargo-test/stages/{{env}}/kargo-demo
      destination:
        name: vk-{{env}}
        namespace: kargo-demo-{{env}}
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true