---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: 'https://github.com/ixxeL-DevOps/GitOps-home.git'
      revision: main
      directories:
        - path: 'talos/manifests/metallb/*'
          exclude: false
  template:
    metadata:
      name: 'metallb-{{ .path.basenameNormalized }}'
      annotations:
        notifications.argoproj.io/subscribe.sync-operation-change.rocketchat: "#infrastructure"
    spec:
      project: infra-network
      destination:
        name: '{{ .path.basenameNormalized }}'
        namespace: metallb-system
      source:
        repoURL: 'https://github.com/ixxeL-DevOps/GitOps-home.git'
        path: '{{.path.path}}'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged

