---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-operator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: talos
        namespace: opentelemetry
  template:
    metadata:
      name: 'otel-operator-{{env}}'
      finalizers: []
    spec:
      project: infra-monitoring
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
        targetRevision: 0.79.0
        chart: opentelemetry-operator
        helm:
          releaseName: 'otel-operator-{{env}}'
          valuesObject:
            fullnameOverride: otel-operator-{{env}}
            manager:
              collectorImage:
                repository: otel/opentelemetry-collector-k8s
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
