---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: infra-pipelines
  destination:
    name: talos
    namespace: rabbitmq
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '*'
    chart: rabbitmq-cluster-operator
    helm:
      releaseName: rabbitmq
      valuesObject:
        global:
          imageRegistry: ""
          imagePullSecrets: []
          defaultStorageClass: ""
          storageClass: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
