# ---
# apiVersion: projects.gitlab.crossplane.io/v1alpha1
# kind: Project
# metadata:
#   name: test-project
#   namespace: crossplane
# spec:
#   forProvider:
#     name: test-project
#     namespaceIdRef:
#       name: test
#   providerConfigRef:
#     name: provider-gitlab
#   writeConnectionSecretToRef:
#     name: gitlab-test-project
#     namespace: crossplane
# ---
# apiVersion: groups.gitlab.crossplane.io/v1alpha1
# kind: Group
# metadata:
#   name: test
# spec:
#   forProvider:
#     name: test
#     parentId: 54224709
#     path: test
#   providerConfigRef:
#     name: provider-gitlab
#   writeConnectionSecretToRef:
#     name: gitlab-test-group
#     namespace: crossplane