---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: github-creds
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: github/k0s
        property: DEVOPS_ORG_PAT
        metadataPolicy: None
