---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: talos
        namespace: crossplane
  template:
    metadata:
      name: 'crossplane-{{env}}'
      finalizers: []
    spec:
      project: infra-core
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://charts.crossplane.io/stable
        targetRevision: 1.*.*
        chart: crossplane
        helm:
          releaseName: 'crossplane-{{env}}'
          valuesObject:
            # provider:
            #   packages:
            #   - xpkg.upbound.io/upbound/provider-gcp-storage:v1.0.2
            #   - xpkg.upbound.io/upbound/provider-gcp-gke:v1.0.2
            #   - xpkg.upbound.io/upbound/provider-gcp-secretmanager:v1.0.2
            #   - xpkg.upbound.io/upbound/provider-gcp-artifact:v1.0.2
            extraObjects:
            - apiVersion: gcp.upbound.io/v1beta1
              kind: ProviderConfig
              metadata:
                name: default
              spec:
                projectID: dogwood-mission-418714
                credentials:
                  source: Secret
                  secretRef:
                    namespace: crossplane
                    name: gke-crossplane
                    key: creds
            - apiVersion: pkg.crossplane.io/v1
              kind: Provider
              metadata:
                name: provider-gcp-artifact
              spec:
                ignoreCrossplaneConstraints: false
                package: xpkg.upbound.io/upbound/provider-gcp-artifact:v1.0.2
                packagePullPolicy: IfNotPresent
                revisionActivationPolicy: Automatic
                revisionHistoryLimit: 1
                runtimeConfigRef:
                  apiVersion: pkg.crossplane.io/v1beta1
                  kind: DeploymentRuntimeConfig
                  name: default
                skipDependencyResolution: false
            - apiVersion: pkg.crossplane.io/v1
              kind: Provider
              metadata:
                name: provider-gcp-gke
              spec:
                ignoreCrossplaneConstraints: false
                package: xpkg.upbound.io/upbound/provider-gcp-gke:v1.0.2
                packagePullPolicy: IfNotPresent
                revisionActivationPolicy: Automatic
                revisionHistoryLimit: 1
                runtimeConfigRef:
                  apiVersion: pkg.crossplane.io/v1beta1
                  kind: DeploymentRuntimeConfig
                  name: default
                skipDependencyResolution: false
            - apiVersion: pkg.crossplane.io/v1
              kind: Provider
              metadata:
                name: provider-gcp-secretmanager
              spec:
                ignoreCrossplaneConstraints: false
                package: xpkg.upbound.io/upbound/provider-gcp-secretmanager:v1.0.2
                packagePullPolicy: IfNotPresent
                revisionActivationPolicy: Automatic
                revisionHistoryLimit: 1
                runtimeConfigRef:
                  apiVersion: pkg.crossplane.io/v1beta1
                  kind: DeploymentRuntimeConfig
                  name: default
                skipDependencyResolution: false
            - apiVersion: pkg.crossplane.io/v1
              kind: Provider
              metadata:
                name: provider-gcp-storage
              spec:
                ignoreCrossplaneConstraints: false
                package: xpkg.upbound.io/upbound/provider-gcp-storage:v1.0.2
                packagePullPolicy: IfNotPresent
                revisionActivationPolicy: Automatic
                revisionHistoryLimit: 1
                runtimeConfigRef:
                  apiVersion: pkg.crossplane.io/v1beta1
                  kind: DeploymentRuntimeConfig
                  name: default
                skipDependencyResolution: false
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jqPathExpressions: 
          - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
          - .spec.template.spec.initContainers[].env[].valueFrom.resourceFieldRef.divisor
