---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: dockerhub-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
  data:
  - secretKey: mysecret
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      key: dockerhub/k0s
      metadataPolicy: None
