---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  mode: daemonset
  config: |
    presets:
      clusterMetrics:
        enabled: true
      hostMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 5s
              static_configs:
                - targets: [localhost:8888]

    exporters:
      debug:
      otlp:
        endpoint: 0.0.0.0:4319

    processors:
      batch:
        timeout: 1s
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 1s

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlp]


