---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
  mode: daemonset
  config: |
    presets:
      clusterMetrics:
        enabled: true
      hostMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      debug:
      prometheus:
        endpoint: ":9090"

    processors:
      batch:
        timeout: 1s
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 1s

