apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: otel-collector-allocator
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        matchLabels:
          release: prom-stack-prod
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [debug]

---
# ---
# apiVersion: opentelemetry.io/v1beta1
# kind: OpenTelemetryCollector
# metadata:
#   name: otel
# spec:
#   mode: statefulset
#   targetAllocator:
#     enabled: true
#     serviceAccount: otel-collector-allocator
#     prometheusCR:
#       enabled: true
#       serviceMonitorSelector:
#         matchLabels:
#           release: prom-stack-prod
#   config:
#     receivers:
#       prometheus:
#         config:
#           scrape_configs:
#           - job_name: otel-collector
#             scrape_interval: 5s
#             static_configs:
#             - targets: [0.0.0.0:8888]
#         target_allocator:
#           endpoint: http://otel-targetallocator
#           interval: 30s
#           collector_id: "${POD_NAME}"

#     exporters:
#       debug:
#         verbosity: detailed
#       prometheus:
#         endpoint: "0.0.0.0:8889"
#         send_timestamps: true
#         metric_expiration: 180m

#     service:
#       pipelines:
#         metrics:
#           receivers:
#           - prometheus
#           processors: []
#           exporters:
#           - debug
#           - prometheus
#       telemetry:
#         logs:
#           level: "debug"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-allocator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator-role
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - probes
      - scrapeconfigs
    verbs:
      - '*'
  - apiGroups: ['']
    resources:
      - namespaces
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources:
      - configmaps
    verbs: ['get']
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ['get', 'list', 'watch']
  - nonResourceURLs: ['/metrics']
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator-rb
subjects:
  - kind: ServiceAccount
    name: otel-collector-allocator
    namespace: opentelemetry
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
  apiGroup: rbac.authorization.k8s.io