---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: test
spec:
  forProvider:
    autoInit: true
    gitignoreTemplate: Terraform
    visibility: public
  providerConfigRef:
    name: github