apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-aps
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: project dedicated to prod application
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
status: {}