---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chartmuseum-creds
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: admin
    kind: ClusterSecretStore
  target:
    name: chartmuseum-creds
  data:
    - secretKey: user
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: chartmuseum/rke2
        property: USER
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: chartmuseum/rke2
        property: PWD
        metadataPolicy: None
