---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-all-in-one
spec:
  provider:
    vault:
      server: "https://vault.fredcorp.com"
      path: "creds"
      version: "v2"
      caProvider:
        type: "ConfigMap"
        namespace: "external-secrets"
        name: "fredcorp-pki-certs"
        key: "vault-pki-certs.pem"
      auth:
        appRole:
          path: "approle"
          roleId: "4dab94e9-3d06-eded-c235-267c2a75a800"
          secretRef:
            name: "secretstore-vault-approle-secretid"
            key: "secret-id-avplugin"
            namespace: "external-secrets"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: admin
spec:
  provider:
    vault:
      server: "https://vault.fredcorp.com"
      path: "admin"
      version: "v2"
      caProvider:
        type: "ConfigMap"
        namespace: "external-secrets"
        name: "fredcorp-pki-certs"
        key: "vault-pki-certs.pem"
      auth:
        appRole:
          path: "approle"
          roleId: "1d7911b7-701e-21f8-7aaf-20c16913e73c"
          secretRef:
            name: "secretstore-vault-approle-secretid"
            key: "secret-id-global"
            namespace: "external-secrets"
