argo-rollouts:
  fullnameOverride: argo-rollouts-talos
  installCRDs: true
  keepCRDs: true
  controller:
    image:
      registry: quay.io
      repository: argoproj/argo-rollouts
    trafficRouterPlugins:
      - name: "argoproj-labs/gatewayAPI" 
        location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.5.0/gatewayapi-plugin-linux-amd64"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prom-stack-talos
  dashboard:
    enabled: true
    readonly: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: argo-rollouts.k8s-app.fredcorp.com
      ingressClassName: "cilium"
      hosts: 
        - argo-rollouts.k8s-app.fredcorp.com
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: argorollouts-tls-cert
          hosts:
            - argo-rollouts.k8s-app.fredcorp.com