argo-rollouts:
  installCRDs: true
  keepCRDs: true
  controller:
    image:
      registry: quay.io
      repository: argoproj/argo-rollouts
    trafficRouterPlugins:
      - name: "argoproj-labs/gatewayAPI" 
        location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.5.0/gatewayapi-plugin-linux-amd64"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prom-stack-talos-test233wd
  dashboard:
    enabled: false
    readonly: false
    ingress:
      enabled: false
