apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    name: rke2
  project: infra-core
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.*.*
    chart: crossplane
    helm:
      releaseName: crossplane
      valuesObject:
        provider:
          packages:
          - xpkg.upbound.io/coopnorge/provider-github:v0.3.2
          - xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.5.0
        configuration:
          packages: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
