apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    name: rke2
  project: infra-core
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.*.*
    chart: crossplane
    helm:
      releaseName: crossplane
      valuesObject:
        provider:
          packages:
          - xpkg.upbound.io/coopnorge/provider-github:v0.3.2
          - xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.5.0
        configuration:
          packages: []
        extraObjects:
          - apiVersion: gitlab.crossplane.io/v1beta1
            kind: ProviderConfig
            metadata:
              name: gitlab-provider
            spec:
              baseURL: https://gitlab.com/
              credentials:
                source: Secret
                secretRef:
                  namespace: crossplane
                  name: crossplane-gitlab-creds
                  key: token
          - apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: crossplane-gitlab-creds
            spec:
              refreshInterval: "60s"
              secretStoreRef:
                name: admin
                kind: ClusterSecretStore
              target:
                name: crossplane-gitlab-creds
              data:
                - secretKey: token
                  remoteRef:
                    conversionStrategy: Default	
                    decodingStrategy: None
                    key: gitlab
                    property: crossplane-token
                    metadataPolicy: None
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=false
      - RespectIgnoreDifferences=true
      - Replace=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
