---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaced-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://gitlab.com/gitops31/k8s-cluster/argocd.git'
        revision: rke2
        directories:
          - path: 'target-ns/*/*'
  template:
    metadata:
      name: gitops-{{path.basenameNormalized}}-{{path[1]}}
      finalizers: []
    spec:
      project: utils
      source:
        repoURL: 'https://gitlab.com/gitops31/k8s-cluster/argocd.git'
        targetRevision: '{{path[1]}}'
        path: '{{path}}'
      destination:
        name: '{{path[1]}}'
        namespace: '{{path.basenameNormalized}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
