---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cri-trusted-certs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: rke2
        namespace: cri-trusted-certs
  template:
    metadata:
      name: 'cri-trusted-certs-{{env}}'
      finalizers: []
    spec:
      project: infra-security
      destination:
        name: '{{env}}'
        namespace: '{{namespace}}'
      sources:
        - repoURL: https://gitlab.com/gitops31/k8s-cluster/infra-tools.git
          targetRevision: '{{env}}'
          path: rke2-trusted-cert
          directory:
            recurse: true
          ref: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - PruneLast=false
          - RespectIgnoreDifferences=true
          - Replace=false
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
