---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo
  namespace: demo
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway
    name: wildcard-tls-gateway
    namespace: kube-system
  hostnames:
  - "demo-web.k8s-app.gateway.fredcorp.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ''	
      kind: Service	
      name: demo-web
      port: 80
      weight: 100