---
apiVersion: v1
kind: LimitRange
metadata:
  name: demo
  namespace: demo
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 750m
    defaultRequest:
      memory: 128Mi
      cpu: 200m
    type: Container