---
name: Renovate check
on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - renovate
  schedule:
  - cron: "0 2 * * *"
  - cron: "0 3 * * *"

concurrency:
  group: auto
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.15
        with:
          configurationFile: renovate.json
          token: ${{ secrets.SUPER_ADMIN_TOKEN }}
          docker-volumes: |
            ${{ github.workspace }}/.npmrc:/github-action/.npmrc
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|NODE_TLS_REJECT_UNAUTHORIZED|NPM_CONFIG_USERCONFIG)$"
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          HELM_USERNAME: 'root'
          HELM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          NPM_CONFIG_USERCONFIG: /github-action/.npmrc
  
