name: Helm Template Generation

on:
  push:
    branches:
      - main
    paths:
      - 'talos/applications/*/talos/*'

jobs:
  generate-helm-templates:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changed Applications
        id: changed-apps
        run: |
          apps=$(git show --name-only --pretty=format: HEAD | xargs -n1 dirname | sort -u | uniq | awk -F'/' '{if (NF > 1) print $(NF-1)}')
          echo "apps=$apps" >> $GITHUB_OUTPUT

      - name: Generate Helm Templates
        env:
          CHANGED_APPS: ${{ steps.changed-apps.outputs.apps }}
        run: |
            helm template "$CHANGED_APPS" "talos/applications/$CHANGED_APPS/talos" > "$CHANGED_APPS-template.yaml"

      - name: Push to Deployment Branch
        env:
          CHANGED_APPS: ${{ steps.changed-apps.outputs.apps }}
          GITHUB_TOKEN: ${{ secrets.SUPER_ADMIN_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git checkout "deploy/talos"
          cp "$CHANGED_APPS-template.yaml" "talos/applications/$CHANGED_APPS/talos"
          
          git add "talos/applications/$CHANGED_APPS/talos/$CHANGED_APPS-template.yaml"
          git commit -m "Update $CHANGED_APPS template for talos environment"
          git push
            